# apiVersion: v1
# kind: Service
# metadata:
#   name: pgadmin
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: pgadmin
#   type: NodePort

# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "pgadmin.fullname" . }}
#   labels:
#     {{- include "pgadmin.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#   selector:
#     {{- include "pgadmin.selectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.selector.app }}