apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  POSTGRES_DB: {{ .Values.database.name | default "postgresdb" }}
  POSTGRES_USER: {{ .Values.database.username | default "admin" }}
  POSTGRES_PASSWORD: {{ .Values.database.password | default "test123" }}
  POSTGRES_INITDB_ARGS: {{ .Values.database.initdbArgs | default "" }}