apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.data.name | default "postgres-pv-volume" }}
  labels:
    type: local
    app: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: {{ .Values.volumes.data.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName | default "postgres-pv-claim" }}
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}